FROM mysql:5.7

# Install selected extensions and other stuff
#RUN apt-get update
#RUN apt-get -y install nano

# Clean up all the mess
#RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
